[package]
name = "evm-disasm"
version = "0.1.0"
edition = "2021"


[dependencies]
hex = "0.4.3"
alloy-primitives = { version = "0.8.19", features = ["rlp"] }
thiserror = "1.0.60"
anyhow = "1.0.72"
once_cell = "1.17.1"

